configuration_filter:
   - name: meanFilter1
     type: filters/MeanFilterDouble
     params: {number_of_observations: 5}
     
slope_filter:
  - name: slopeFilter
    type: filters/SlopeFilter
    params: {weight: 0.5, slopeCritical: 0.7854}
  - name: stepFilter
    type: filters/StepFilter
    params: {weight: 0.5, stepCritical: 0.2, windowSize: 3}
  - name: roughnessFilter
    type: filters/RoughnessFilter
    params: {weight: 0.5, roughnessCritical: 0.1, roughnessEstimationRadius: 0.3}