configuration_filter:
   - name: meanFilter1
     type: filters/MeanFilterDouble
     params: {number_of_observations: 5}
     
slope_filter:
  - name: slopeFilter
    type: filters/SlopeFilter
    params: {weight: 0.5, slopeCritical: 0.7854}