# Traversability map filter parameters
traversability_map_filters:
 - name: inpaintFilter
   type: gridMapFilters/InpaintFilter
   params:
      map_type: elevation_inpaint
      radius: 5.0
      input_layer: elevation
  - name: surfaceNormalsFilter
    type: traversabilityFilters/SurfaceNormalsFilter
    params:
      input_layer: elevation
      estimation_radius: 0.05
      surface_normal_positive_axis: "z"
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 1.0
  - name: stepFilter
    type: traversabilityFilters/StepFilter
    params:
      input_layer: elevation
      map_type: traversability_step
      critical_value: 0.12
      first_window_radius: 0.04
      second_window_radius: 0.04
      critical_cell_number: 4
  - name: roughnessFilter
    type: traversabilityFilters/RoughnessFilter
    params:
      input_layer: elevation
      map_type: traversability_roughness
      critical_value: 0.05
      estimation_radius: 0.05
# - name: minFilter
#   type: gridMapFilters/MinFilter
#   params:
#    layers: [traversability_slope, traversability_step, traversability_roughness]
#    layer_out: traversability
# - name: lowerThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    lower_threshold: 0.2
#    set_to: 0.0
#    layers: [traversability]
# - name: upperThresholdFilter
#   type: gridMapFilters/ThresholdFilter
#   params:
#    upper_threshold: 0.9
#    set_to: 1.0
#    layers: [traversability]
  - name: weightedSumFilter
    type: gridMapFilters/WeightedSumFilter
    params:
      layers: [traversability_slope, traversability_step, traversability_roughness]
      weights: [1, 1, 1]
      layer_out: traversability
      normalize: 1
# - name: meanInRadiusFilter
#    type: gridMapFilters/MeanInRadiusFilter
#    params:
#      map_type: elevation_mean_in_radius
#      radius: 0.05
#      input_layer: elevation
# - name: minInRadiusFilter
#   type: gridMapFilters/MinInRadiusFilter
#   params:
#      map_type: footscore_min_in_radius
#      radius: 0.02
#      input_layer: footscore
- name: zeroOneFilter
   type: gridMapFilters/ZeroOneFilter
   params:
      map_type: zero_one
      threshold: 0.8
      input_layer: footscore
  - name: deletionFilter
    type: gridMapFilters/DeletionFilter
    params:
      layers: [surface_normal_x, surface_normal_y, surface_normal_z]
