submap_service: "/elevation_mapping_long_range/get_grid_map"
robot_frame_id: "base"
map_frame_id: "map"
update_rate: 4.0
map_center_x: 1.5
map_center_y: 0.0
map_length_x: 5.0
map_length_y: 5.0

traversability_map_filters:
  - name: slopeFilter
    type: filters/SlopeFilter
    params:
     mapType: traversability_slope
     criticalValue: 0.7854
  - name: stepFilter
    type: filters/StepFilter
    params:
     mapType: traversability_step
     criticalValue: 0.2
     windowRadius: 0.2
  - name: roughnessFilter
    type: filters/RoughnessFilter
    params:
     mapType: traversability_roughness
     criticalValue: 0.1
     estimationRadius: 0.3
#  - name: weightedSumFilter
#    type: filters/WeightedSumFilter
#    params:
#     filterTypes: [traversability_slope, traversability_step, traversability_roughness]
#     filterWeights: [1, 1, 1]
#     typeOut: traversability
#     normalize: 1
  - name: minFilter
    type: filters/MinFilter
    params:
     filterTypes: [traversability_slope, traversability_step, traversability_roughness]
     typeOut: traversability
  - name: thresholdFilter
    type: filters/ThresholdFilter
    params:
     lowerThreshold: 0.1
     upperThreshold: 0.9
     thresholdTypes: [traversability]
#  - name: deletionFilter
#    type: filters/DeletionFilter
#    params:
#     deletionTypes: [traversability_slope, traversability_step, traversability_roughness]