submap_service: "/elevation_mapping_long_range/get_grid_map"
robot_frame_id: "base"
map_frame_id: "topocentric"
update_rate: 4.0
map_center_x: 1.5
map_center_y: 0.0
map_length_x: 5.0
map_length_y: 5.0

elevation_filter_chain:
  filter_chain:
  - name: slopeFilter
    type: SlopeFilter
    params: