rate: 1.0
extrapolation_duration: 1.0
footprint_radius: 0.35
service_to_call: /traversability_estimation/check_footprint_path
robot_pose_topic: pose
twist_topic: twist
use_twist_with_covariance: false