rate: 2.0
extrapolation_duration: 1.0
footprint_radius: 0.35
footprint_polygon: [[0.355, 0.32, 0.0], [0.355, -0.32, 0.0], [-0.355, -0.32, 0.0], [-0.355, 0.32, 0.0]]
service_to_call: /traversability_estimation/check_footprint_path
robot_pose_topic: /state_estimator/pose
robot_twist_topic: /state_estimator/twist
